[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/oriola-denim-0.0.1-SNAPSHOT.jar --spring.profiles.active=railway"