services:
  - type: web
    name: oriola-denim
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    buildCommand: mvn clean install -DskipTests

